using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Console;

namespace Pokedex
{
    public class Pokedexx
    {
        public Pokedexx()
        {
            this.InicializaLista();
        }
        private List<Pokemon> pokemons;
        public List<Pokemon> Pokemons
        {
            get { return pokemons; }
        }
        private void InicializaLista()
        {
            this.pokemons = new List<Pokemon>();
            Pokemon p = new Pokemon("Bulbasauro", "pokémon tipo planta");
            this.pokemons.Add(p);
            p = new Pokemon("Ivysaur", "pokémon tipo planta e venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Venusaur", "pokémon tipo planta e venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Charmander", "pokémon tipo fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Charmeleon", "pokémon tipo fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Charizard", "pokémon tipo fogo e voador");
            this.pokemons.Add(p);
            p = new Pokemon("Squirtle", "pokémon de água");
            this.pokemons.Add(p);
            p = new Pokemon("Wartortle", "pokémon de água");
            this.pokemons.Add(p);
            p = new Pokemon("Blastoise", "pokémon de agua");
            this.pokemons.Add(p);
            p = new Pokemon("Caterpie", "Pokémon inseto");
            this.pokemons.Add(p);
            p = new Pokemon("Metapod", "Pokémon inseto");
            this.pokemons.Add(p);
            p = new Pokemon("Butterfree", "Pokémon tipo inseto e voador");
            this.pokemons.Add(p);
            p = new Pokemon("Weedle", "pokémon tipo planta e venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Kakuna", "pokémon tipo planta e venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Beedrill", "pokémon tipo planta e venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Pidgey", "pokémon Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Pidgeotto", "pokémon Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Pidgeot", "pokémon Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Rattata", "pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Raticate", "pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Spearow", "pokémon Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Fearow", "pokémon Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Ekans", "Pokémon Venenoso");
            this.pokemons.Add(p);  
            p = new Pokemon("Arbok", "Venenoso");
            this.pokemons.Add(p);   
            p = new Pokemon("Pikachu", "Elétrico");
            this.pokemons.Add(p);   
            p = new Pokemon("Raichu", "Elétrico");
            this.pokemons.Add(p); 
            p = new Pokemon("Sandshrew", "Pokémon Terrestre");
            this.pokemons.Add(p); 
            p = new Pokemon("Sandslash", "Pokémon Terrestre");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidoran", "Pokémon Venenoso");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidorina", "Pokémon Venenoso");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidoqueen", "Pokémon Venenoso e Terrestre");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidoran", "Pokémon Venenoso");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidorino", "Pokémon Venenoso");
            this.pokemons.Add(p); 
            p = new Pokemon("Nidoking", "Pokémon Venenoso e Terrestre");
            this.pokemons.Add(p); 
            p = new Pokemon("Clefairy", "Pokémon tipo Fada");
            this.pokemons.Add(p); 
            p = new Pokemon("Clefable", "Pokémon tipo Fada");
            this.pokemons.Add(p); 
            p = new Pokemon("Vulpix", "Pokémon de Fogo");
            this.pokemons.Add(p); 
            p = new Pokemon("Ninetales", "Pokémon de Fogo");
            this.pokemons.Add(p); 
            p = new Pokemon("Jigglypuff", "Pokémon Normal e tipo Fada");
            this.pokemons.Add(p); 
            p = new Pokemon("Wigglytuff", "Pokémon Normal e tipo Fada");
            this.pokemons.Add(p); 
            p = new Pokemon("Zubat", "Pokémon Venenoso e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Golbat", "Pokémon Venenoso e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Oddish", "Pokémon Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Gloom", "Pokémon Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Vileplume", "Pokémon Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Paras", "Pokémon tipo Inseto e Planta");
            this.pokemons.Add(p);
            p = new Pokemon("Parasect", "Pokémon tipo Inseto e Planta");
            this.pokemons.Add(p);
            p = new Pokemon("Venonat", "Pokémon tipo Inseto e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Venomoth", "Pokémon tipo Inseto e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Diglett", "Pokémon Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Dugtrio", "Pokémon Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Meowth", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Persian", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Psyduck", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Golduck", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Mankey", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Primeape", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Growlithe", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Arcanine", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Poliwag", "Pokémon Tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Poliwhirl", "Pokémon Tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Poliwrath", "Pokémon Tipo água e Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Abra", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Kadabra", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Alakazam", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Machop", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Machoke", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Machamp", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Bellsprout", "Pokémon Tipo Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Weepinbell", "Pokémon Tipo Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Victreebel", "Pokémon Tipo Planta e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Tentacool", "Pokémon tipo água e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Tentacruel", "Pokémon tipo água e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Geodude", "Pokémon tipo Pedra e Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Graveler", "Pokémon tipo Pedra e Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Golem", "Pokémon tipo Pedra e Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Ponyta", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Rapidash", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Slowpoke", "Pokémon tipo água e Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Slowbro", "Pokémon tipo água e Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Magnemite", "Pokémon tipo Elétrico e Aço");
            this.pokemons.Add(p);
            p = new Pokemon("Magneton", "Pokémon tipo Elétrico e Aço");
            this.pokemons.Add(p);
            p = new Pokemon("Farfetch'd", "Pokémon tipo Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Doduo", "Pokémon tipo Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Dodrio", "Pokémon tipo Normal e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Seel", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Dewgong", "Pokémon tipo água e Gelo");
            this.pokemons.Add(p);
            p = new Pokemon("Grimer", "Pokémon Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Muk", "Pokémon Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Shellder", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Cloyster", "Pokémon tipo água e Gelo");
            this.pokemons.Add(p);
            p = new Pokemon("Gastly", "Pokémon tipo Fantasma e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Haunter", "Pokémon tipo Fantasma e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Gengar", "Pokémon tipo Fantasma e Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Onix", "Pokémon tipo Pedra e Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Drowzee", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Hypno", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Krabby", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Kingler", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Voltorb", "Pokémon tipo Elétrico");
            this.pokemons.Add(p);
            p = new Pokemon("Electrode", "Pokémon tipo Elétrico");
            this.pokemons.Add(p);
            p = new Pokemon("Exeggcute", "Pokémon tipo Planta e Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Exeggutor", "Pokémon tipo Planta e Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Cubone", "Pokémon Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Marowak", "Pokémon Terrestre");
            this.pokemons.Add(p);
            p = new Pokemon("Hitmonlee", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Hitmonchan", "Pokémon Lutador");
            this.pokemons.Add(p);
            p = new Pokemon("Lickitung", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Koffing", "Pokémon Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Weezing", "Pokémon Venenoso");
            this.pokemons.Add(p);
            p = new Pokemon("Rhyhorn", "Pokémon tipo Terrestre e Pedra");
            this.pokemons.Add(p);
            p = new Pokemon("Rhydon", "Pokémon tipo Terrestre e Pedra");
            this.pokemons.Add(p);
            p = new Pokemon("Chansey", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Tangela", "Pokémon tipo Planta");
            this.pokemons.Add(p);
            p = new Pokemon("Kangaskhan", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Horsea", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Seadra", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Goldeen", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Seaking", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Staryu", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Starmie", "Pokémon tipo água e Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Mr. Mime", "Pokémon tipo Psiquico e Fada");
            this.pokemons.Add(p);
            p = new Pokemon("Scyther", "Pokémon tipo Inseto e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Jynx", "Pokémon tipo Gelo e Psquico");
            this.pokemons.Add(p);
            p = new Pokemon("Electabuzz", "Pokémon Elétrico");
            this.pokemons.Add(p);
            p = new Pokemon("Magmar", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Pinsir", "Pokémon tipo Inseto");
            this.pokemons.Add(p);
            p = new Pokemon("Tauros", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Magikarp", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Gyarados", "Pokémon tipo água e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Lapras", "Pokémon tipo água e Gelo");
            this.pokemons.Add(p);
            p = new Pokemon("Ditto", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Eevee", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Vaporeon", "Pokémon tipo água");
            this.pokemons.Add(p);
            p = new Pokemon("Jolteon", "Pokémon Elétrico");
            this.pokemons.Add(p);
            p = new Pokemon("Flareon", "Pokémon de Fogo");
            this.pokemons.Add(p);
            p = new Pokemon("Porygon", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Omanyte", "Pokémon tipo Pedra e Água");
            this.pokemons.Add(p);
            p = new Pokemon("Omastar", "Pokémon tipo Pedra e Água");
            this.pokemons.Add(p);
            p = new Pokemon("Kabuto", "Pokémon tipo Pedra e Água");
            this.pokemons.Add(p);
            p = new Pokemon("Kabutops", "Pokémon tipo Pedra e Água");
            this.pokemons.Add(p);
            p = new Pokemon("Aerodactyl", "Pokémon tipo Pedra e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Snorlax", "Pokémon Normal");
            this.pokemons.Add(p);
            p = new Pokemon("Articuno", "Pokémon tipo Gelo e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Zapdos", "Pokémon tipo Elétrico e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Moltres", "Pokémon tipo Fogo e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Dratini", "Pokémon tipo Dragão");
            this.pokemons.Add(p);
            p = new Pokemon("Dragonair", "Pokémon tipo Dragão");
            this.pokemons.Add(p);
            p = new Pokemon("Dragonite", "Pokémon tipo Dragão e Voador");
            this.pokemons.Add(p);
            p = new Pokemon("Mewtwo", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Mew", "Pokémon Psiquico");
            this.pokemons.Add(p);
            p = new Pokemon("Meltan", "Pokémon de Aço");
            this.pokemons.Add(p);
            p = new Pokemon("Melmetal", "Pokémon de Aço");
            this.pokemons.Add(p);
        }
        public void ListarPokemons()
        {
            for(int i = 0; i < this.Pokemons.Count; i++)
            {
                this.Pokemons[i].ExibirDadosPokemon();
            }
        }

    }
}